name: Workflow for group 14  # Name of your GitHub Actions workflow

on:  # Event that triggers the workflow
  push:  # Triggered on every push to the repository
    branches: ["main"]  # Only trigger for pushes to the main branch
    
jobs: 
  build:  # Define a job named 'build'
    runs-on: ubuntu-latest  # Specify the operating system for the job
    
    steps:  # List of steps to be executed in the job
      - name: Checkout code  # Checkout the repository's code
        uses: actions/checkout@v3  # Use the actions/checkout action

      - name: Setup R environment  # Set up R environment
        uses: r-lib/actions/setup-r@v2  # Use the r-lib/actions/setup-r action
        with:
          r-version: '4.2.0'  # Specify the R version to be used

      - name: Cache R packages  # Cache R packages to improve workflow speed
        uses: actions/cache@v3  # Use the actions/cache action
        with:
          path: ${{ env.R_LIBS_USER }}  # Specify the path to R packages
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}  # Unique key for caching
          restore-keys: |  # Specify keys to restore cache
            ${{ runner.os }}-r-

      - name: Install R packages  # Install R packages if not cached
        if: steps.cache.outputs.cache-hit != 'true'  # Condition to check if cache hit is false
        run: |
          Rscript -e 'install.packages(c("DBI", "RSQLite", "ggplot2", "lubridate","readr"), dependencies = TRUE)'  # Install required R packages

      - name: Execute R script  # Execute R script
        run: |
          Rscript R_Scripts/Prep.R  # Run the Prep.R script

      - name: Configure Git  # Configure Git user
        run: |
          git config --global user.email "natvaraaom1998@gmail.com"  # Set Git user email
          git config --global user.name "natvaraaom"  # Set Git user name
          git add --all Database  # Specify where to add files

      - name: Commit updated database  # Commit updated database file
        run: |
          git commit -m "Update database with new data" || echo "No changes to commit"  # Commit changes with a message or handle no changes

      - name: Push changes  # Push changes to remote repository
        uses: ad-m/github-push-action@v0.6.0  # Use the ad-m/github-push-action
        with:
          github_token: ${{ secrets.DM_TKN }}  # GitHub token for authentication
          branch: main  # Specify the branch to push changes
